### ISSUE TITLE
Add Variables

### ISSUE THREAD

**Issue by George-lewis** [George-lewis/rustcalc#3]
# Description

Allow users to define variables at runtime and use them in expressions.

## Overview

It should look similar to the following:

```
> $
[ ans ; 0.000 ]
> 1 + 3
[ 1 + 3 ] => 4.000
> $
[ ans ; 4.000 ]
> x = $ans/2 pow 2
[ x = $ans / 2^2 ] => 1.000
> $
[ ans ; 4.000 ]
[ x ; 1.000 ]
```

## Details

A new struct will have to be added named `Variable`, several library functions will accept a `&[Variable]` and tokenize, and then evaluate accordingly. A new error type will have to be added for unknown variables and several modifications will have to be made to the CLI code to support it all.

---

Please target branch `variables`

**Comment by kinseyda** [comment]
I can take this issue

**Comment by George-lewis** [comment]
Sounds good to me
